package server

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/rs/zerolog"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/agentstation/starport/internal/apikeys"
	"github.com/agentstation/starport/internal/chatui"
	"github.com/agentstation/starport/internal/storage"
)

// TestChatUIToAPIAuthentication tests that a key generated by ChatUI
// can be used to authenticate API requests
func TestChatUIToAPIAuthentication(t *testing.T) {
	// Setup shared storage
	store := storage.NewMockStore()
	logger := zerolog.Nop()

	// Step 1: Create ChatUI handler and generate a key
	chatuiConfig := chatui.Config{
		Title:       "Test Chat",
		Theme:       "light",
		AllowKeyGen: true,
		APIBaseURL:  "http://localhost:8080",
		Store:       store,
	}

	chatuiHandler, err := chatui.NewHandler(&logger, chatuiConfig)
	require.NoError(t, err)

	// Generate a key
	req := httptest.NewRequest(http.MethodPost, "/chat/generate-key", nil)
	rec := httptest.NewRecorder()
	chatuiHandler.GenerateKey(rec, req)

	require.Equal(t, http.StatusOK, rec.Code, "Key generation should succeed")

	var keyResponse map[string]interface{}
	err = json.Unmarshal(rec.Body.Bytes(), &keyResponse)
	require.NoError(t, err)

	apiKey, ok := keyResponse["key"].(string)
	require.True(t, ok, "Response should contain key")
	require.NotEmpty(t, apiKey, "API key should not be empty")

	t.Logf("Generated API key: %s", apiKey)
	t.Logf("Key ID: %s", keyResponse["key_id"])

	// Step 2: Create auth middleware with the same store
	auth := NewAuthMiddleware(store)

	// Create a protected handler
	protectedHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Verify context has the expected values
		keyFromContext := r.Context().Value(ContextKeyAPIKey).(string)
		assert.Equal(t, apiKey, keyFromContext)

		keyIDFromContext := r.Context().Value(ContextKeyAPIKeyID).(string)
		assert.NotEmpty(t, keyIDFromContext)

		modelFromContext := r.Context().Value(ContextKeyAPIKeyModel).(*apikeys.APIKey)
		assert.NotNil(t, modelFromContext)
		assert.Contains(t, modelFromContext.Scopes, "chat:write")
		assert.Contains(t, modelFromContext.Scopes, "models:read")

		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"authenticated": true}`))
	})

	// Wrap with auth middleware
	handler := auth.RequireAPIKey(protectedHandler)

	// Step 3: Make authenticated request
	authReq := httptest.NewRequest(http.MethodGet, "/api/v1/test", nil)
	authReq.Header.Set("Authorization", "Bearer "+apiKey)
	authRec := httptest.NewRecorder()

	handler.ServeHTTP(authRec, authReq)

	assert.Equal(t, http.StatusOK, authRec.Code, "Authenticated request should succeed")
	assert.Contains(t, authRec.Body.String(), "authenticated")

	// Step 4: Verify the key cannot be used if disabled
	// Get the key from storage and disable it
	keyID := keyResponse["key_id"].(string)
	keyData, err := store.Get(context.Background(), storage.APIKeyKey(keyID))
	require.NoError(t, err)

	var apiKeyModel apikeys.APIKey
	err = storage.Deserialize(keyData, &apiKeyModel)
	require.NoError(t, err)

	// Disable the key
	apiKeyModel.Active = false
	keyData, err = storage.Serialize(&apiKeyModel)
	require.NoError(t, err)
	err = store.Set(context.Background(), storage.APIKeyKey(keyID), keyData)
	require.NoError(t, err)

	// Try to use the disabled key
	disabledReq := httptest.NewRequest(http.MethodGet, "/api/v1/test", nil)
	disabledReq.Header.Set("Authorization", "Bearer "+apiKey)
	disabledRec := httptest.NewRecorder()

	handler.ServeHTTP(disabledRec, disabledReq)

	assert.Equal(t, http.StatusForbidden, disabledRec.Code)
	assert.Contains(t, disabledRec.Body.String(), "API key is disabled")
}

// TestMultipleKeyGeneration tests that multiple keys can be generated
// and each one works independently
func TestMultipleKeyGeneration(t *testing.T) {
	store := storage.NewMockStore()
	logger := zerolog.Nop()

	chatuiConfig := chatui.Config{
		Title:       "Test Chat",
		Theme:       "light",
		AllowKeyGen: true,
		APIBaseURL:  "http://localhost:8080",
		Store:       store,
	}

	chatuiHandler, err := chatui.NewHandler(&logger, chatuiConfig)
	require.NoError(t, err)

	// Generate multiple keys
	var keys []string
	for i := 0; i < 3; i++ {
		req := httptest.NewRequest(http.MethodPost, "/chat/generate-key", nil)
		rec := httptest.NewRecorder()
		chatuiHandler.GenerateKey(rec, req)

		require.Equal(t, http.StatusOK, rec.Code)

		var keyResponse map[string]interface{}
		err = json.Unmarshal(rec.Body.Bytes(), &keyResponse)
		require.NoError(t, err)

		apiKey := keyResponse["key"].(string)
		keys = append(keys, apiKey)
		t.Logf("Generated key %d: %s", i+1, apiKey)
	}

	// Verify each key works independently
	auth := NewAuthMiddleware(store)
	successHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
	handler := auth.RequireAPIKey(successHandler)

	for i, apiKey := range keys {
		req := httptest.NewRequest(http.MethodGet, "/api/v1/test", nil)
		req.Header.Set("Authorization", "Bearer "+apiKey)
		rec := httptest.NewRecorder()

		handler.ServeHTTP(rec, req)
		assert.Equal(t, http.StatusOK, rec.Code, "Key %d should authenticate successfully", i+1)
	}
}

// TestKeyHashVerification verifies that the hash verification works correctly
func TestKeyHashVerification(t *testing.T) {
	store := storage.NewMockStore()

	// Manually create a key with known values
	keyValue := "sk-starport-test-verification"
	keyID := "STARPORT_verification"

	// Calculate correct hash
	hash := sha256.Sum256([]byte(keyValue))
	correctHash := hex.EncodeToString(hash[:])

	// Store the key with WRONG hash
	apiKey := &apikeys.APIKey{
		ID:        keyID,
		Name:      "Test Key",
		Hash:      "intentionally-wrong-hash",
		Scopes:    []string{"test"},
		Active:    true,
		CreatedAt: time.Now(),
	}

	ctx := context.Background()
	keyData, err := storage.Serialize(apiKey)
	require.NoError(t, err)

	// Store the key
	err = store.Set(ctx, storage.APIKeyKey(keyID), keyData)
	require.NoError(t, err)

	// Store hash mapping (with correct hash)
	err = store.Set(ctx, storage.APIKeyHashKey(correctHash), []byte(keyID))
	require.NoError(t, err)

	// Try to authenticate - should fail due to hash mismatch
	auth := NewAuthMiddleware(store)
	handler := auth.RequireAPIKey(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		t.Fatal("Handler should not be called with mismatched hash")
	}))

	req := httptest.NewRequest(http.MethodGet, "/test", nil)
	req.Header.Set("Authorization", "Bearer "+keyValue)
	rec := httptest.NewRecorder()

	handler.ServeHTTP(rec, req)

	assert.Equal(t, http.StatusUnauthorized, rec.Code)
	assert.Contains(t, rec.Body.String(), "Invalid API key")
}
