package config

import (
	"bytes"
	"context"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"strings"

	"github.com/agentstation/starmap/pkg/productpaths"
)

// ReferenceDirectory is the repository directory of the generated reference
// files. The docs build includes it.
const ReferenceDirectory = "docs/site/generated"

// referenceGenerator names the command that writes the reference files.
const referenceGenerator = "scripts/docsgen"

const referenceNotice = "<!-- Generated by scripts/docsgen. Do not edit. Run make docs-generate. -->\n\n"

const referenceSource = "The `scripts/docsgen` generator writes this page from the source code. Do not edit this page. To update it, run `make docs-generate`.\n\n"

// ReferenceFile is one generated documentation file.
type ReferenceFile struct {
	// Name is the file name in ReferenceDirectory.
	Name string
	Data []byte
}

// ReferenceFiles renders the settings inventory and the default file
// inventory of each release platform. The result holds descriptors and
// defaults only. It holds no value from the process environment or from a
// configuration file.
func ReferenceFiles(ctx context.Context) ([]ReferenceFile, error) {
	settings := newSettingsInventory()
	settingsJSON, err := referenceJSON(settings)
	if err != nil {
		return nil, err
	}
	placeholder, err := defaultFileManifest(ctx)
	if err != nil {
		return nil, fmt.Errorf("default file manifest: %w", err)
	}
	files := []ReferenceFile{
		{Name: "settings.json", Data: settingsJSON},
		{Name: "settings.md", Data: settings.markdown()},
	}
	manifests := make([]productpaths.FileManifest, len(referencePlatforms))
	for index, platform := range referencePlatforms {
		manifests[index] = platform.manifest(placeholder)
		data, err := referenceJSON(manifests[index])
		if err != nil {
			return nil, err
		}
		files = append(files, ReferenceFile{Name: "files-" + platform.ID + ".json", Data: data})
	}
	return append(files, ReferenceFile{Name: "files.md", Data: filesMarkdown(manifests)}), nil
}

func referenceJSON(value any) ([]byte, error) {
	data, err := json.Marshal(value, json.Deterministic(true), jsontext.WithIndent("  "))
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

func (inventory settingsInventory) markdown() []byte {
	var page bytes.Buffer
	page.WriteString(referenceNotice + "# Settings reference\n\n" + referenceSource)
	page.WriteString("This page lists the name, the type, and the default of each setting. It shows no value from a deployment.\n\n")
	page.WriteString("## Catalog settings\n\n")
	page.WriteString("The Starmap catalog descriptors define these settings. The configuration view and the configuration save use the same list.\n\n")
	page.WriteString("| Variable | Type | Scope | Default | Mutability | Sensitive |\n| --- | --- | --- | --- | --- | --- |\n")
	for _, setting := range inventory.Schema {
		fmt.Fprintf(&page, "| `%s` | %s | %s | %s | %s | %s |\n", setting.Environment, setting.Type, setting.Scope,
			markdownDefault(setting.Default, setting.Unit), setting.Mutability, markdownYesNo(setting.Sensitive))
	}
	page.WriteString("\n## Gateway settings\n\n")
	page.WriteString("The `env` tags of the Starport configuration define these settings. The `starport config show` command shows a secret setting as `<redacted>`. ")
	page.WriteString("A platform path default is in the data root. The file reference gives the root for each platform.\n")
	section := ""
	for _, setting := range inventory.Environment {
		if setting.Section != section {
			section = setting.Section
			fmt.Fprintf(&page, "\n### %s\n\n| Variable | Type | Default | Secret |\n| --- | --- | --- | --- |\n", section)
		}
		fallback := markdownDefault(setting.Default, "")
		if setting.DefaultSource == defaultSourcePlatformPath {
			fallback = "Platform path"
		}
		fmt.Fprintf(&page, "| `%s` | `%s` | %s | %s |\n", setting.Name, setting.Type, fallback, markdownYesNo(setting.Secret))
	}
	return page.Bytes()
}

func filesMarkdown(manifests []productpaths.FileManifest) []byte {
	var page bytes.Buffer
	page.WriteString(referenceNotice + "# File reference\n\n" + referenceSource)
	page.WriteString("This page lists the files and directories that Starport can use with the default configuration. ")
	page.WriteString("A path that starts with `~` is in your home directory. A setting in the Selectors column can move the path. ")
	page.WriteString("Starport creates only the files that the selected backend and operation use. ")
	page.WriteString("To see the report for your configuration, run `starport config paths --files`.\n")
	for index, platform := range referencePlatforms {
		report := manifests[index]
		fmt.Fprintf(&page, "\n## %s\n\n| Root | Path |\n| --- | --- |\n", platform.Title)
		for _, root := range referenceRoots {
			fmt.Fprintf(&page, "| %s | %s |\n", root, markdownCode(report.Roots[root].Path))
		}
		page.WriteString("\n| ID | Kind | Path | Availability | Access | Selectors |\n| --- | --- | --- | --- | --- | --- |\n")
		for _, entry := range report.Files {
			path := "Not selected"
			if entry.Location.Path != "" {
				path = markdownCode(entry.Location.Path)
			}
			selectors := make([]string, len(entry.Policy.Selectors))
			for position, selector := range entry.Policy.Selectors {
				selectors[position] = markdownCode(selector)
			}
			fmt.Fprintf(&page, "| `%s` | %s | %s | %s | %s | %s |\n", entry.ID, entry.Kind, path, entry.Availability,
				entry.Policy.Access, strings.Join(selectors, ", "))
		}
	}
	return page.Bytes()
}

func markdownDefault(value, unit string) string {
	if value == "" {
		return "None"
	}
	if unit != "" {
		return markdownCode(value) + " " + markdownCell(unit)
	}
	return markdownCode(value)
}

func markdownYesNo(value bool) string {
	if value {
		return "Yes"
	}
	return "No"
}

// markdownCode returns a table cell that shows the value as code.
func markdownCode(value string) string {
	return "`" + markdownCell(value) + "`"
}

func markdownCell(value string) string {
	return strings.NewReplacer("|", `\|`, "\n", " ").Replace(value)
}
